### PR TITLE
s3

### PR DESCRIPTION
**Pull request by ammedmar**

### CODE REVIEW

**Comment by gf2078** [comment]
I disagree with the change from "co-orientations can be "pulled back"" to "co-orientations can be "pulled-back"". If anything, a change like this would probably be to "pull-backed." But I think the original version is best - I don't think "pulled-back" is grammatical in English.

**Comment by gf2078** [comment]
I'm not sure I feel strongly about it, but I think I also prefer "nontrivial" to "non-trivial". We need the hyphen in "co-orientation" since "coorientation" has a problem with the double o (in classical times, we probably would have put an umlaut over the second o). But there's no such problem with nontrivial. Wikipedia even has "nontrivial" as the preferred version in: https://en.wikipedia.org/wiki/Triviality_(mathematics)

**Comment by gf2078** [comment]
You have a commit with message "Replace orientation "for" by "of" ", but I don't think you actually made that change in that commit (the only change I see is a ~ in the citation).

**Comment by gf2078** [comment]
You wrote:
\medskip\noindent\textbf{Fiber products of immersions.}
% anibal: should this be a \subsubsection?

I think that's a good idea.

**Comment by gf2078** [comment]
You wrote: "\medskip\noindent\textbf{Functoriality of pullbacks.}
The co-oriented pullback construction is functorial in the following sense.
% Consider a \subsubsection?"
In this case I think having one further level down would be slightly better, but I'm also okay with this being a \subsubsection.

**Comment by gf2078** [comment]
Okay, I think I'm good on most of Pull Request #6. Let's discuss the issues I raise in the preceding comments, and once we get those resolved I'll approve. If we want to involve Dev, email might be better. For now I skipped over #5, since I think that's where Dev's new introduction is and I just wanted to look at the "easy stuff" tonight.

**Comment by ammedmar** [comment]
> I disagree with the change from "co-orientations can be "pulled back"" to "co-orientations can be "pulled-back"". If anything, a change like this would probably be to "pull-backed." But I think the original version is best - I don't think "pulled-back" is grammatical in English.

Reverted

> I'm not sure I feel strongly about it, but I think I also prefer "nontrivial" to "non-trivial". We need the hyphen in "co-orientation" since "coorientation" has a problem with the double o (in classical times, we probably would have put an umlaut over the second o). But there's no such problem with nontrivial. Wikipedia even has "nontrivial" as the preferred version in: https://en.wikipedia.org/wiki/Triviality_(mathematics)

Reverted

> You have a commit with message "Replace orientation "for" by "of" ", but I don't think you actually made that change in that commit (the only change I see is a ~ in the citation).

Yeah, I don't seem to find what I had in mind so I changed the commit message to: Add ~ to a theorem number in citation. 

> You wrote: \medskip\noindent\textbf{Fiber products of immersions.} % anibal: should this be a \subsubsection?
> I think that's a good idea.

Change made

> You wrote: "\medskip\noindent\textbf{Functoriality of pullbacks.} The co-oriented pullback construction is functorial in the following sense. % Consider a \subsubsection?" In this case I think having one further level down would be slightly better, but I'm also okay with this being a \subsubsection.

The natural level down is \paragraph but it doesn't do much in the amsart class. When I look at the other sections closer I will see if wee need to redefine \paragraph to be more like what \medskip\noindent\textbf{} does. For now, no change made here.

**Comment by gf2078** [comment]
yeah, I like \paragraph and \subparagraph in the file class I usually use, but I agree it's not very good in the class we're using, which is why I did the  \medskip\noindent\textbf{} thing. Seriously, though, I'd be fine with making this a \subsubsection.

**Comment by ammedmar** [comment]
> yeah, I like \paragraph and \subparagraph in the file class I usually use, but I agree it's not very good in the class we're using, which is why I did the \medskip\noindent\textbf{} thing. Seriously, though, I'd be fine with making this a \subsubsection.

Done

**Review by gf2078 — APPROVED** [review]

**Pull request merged**
