### PR TITLE
Correction to Lemma in 3.5.2

### PR DESCRIPTION
**Pull request by gf2078**
I think I've got the lemma fixed up. Not sure if you want to read it before or after we merge it to main, but I figured I'd give a pull request a try.

### CODE REVIEW

**Review by ammedmar — APPROVED** [review]
It looks good to me. I fixed some typos and some code conventions. I mention that I also merged main to this branch so it is easy to merge this branch to main, (no conflicts to worry about). Feel free to merge when you want.

**Comment by gf2078** [comment]
Yeah, I’m a little confused there. Why merge one way then the other instead of just merging the branch into main?

--
Greg Friedman
Professor and Department Chair
John William and Helen Stubbs Potter Professor of Mathematics
Department of Mathematics
Texas Christian University

**Comment by ammedmar** [comment]
The branch could not be merged into main without conflicts, so those needed to be resolved before merging. The process of resolving conflicts lead to a merge of main to the branch, kind of preparing it to be compatible with main, and then the marge of the branch into main was unobstructed.

**Comment by gf2078** [comment]
But aren’t those the same conflicts that would have to be resolved in merging the branch into main? So I’m not clear why going one way is better than going the other.

I did still have one conflict to fix, but I think that’s because I already had some uncommitted changes to main while you were doing the merge. In fact, thank god for auto-stashing, or I would have lost some stuff, but I think I did it all correctly in the end.

--
Greg Friedman
Professor and Department Chair
John William and Helen Stubbs Potter Professor of Mathematics
Department of Mathematics
Texas Christian University

**Pull request merged**
