### PR TITLE
s1

### PR DESCRIPTION
**Pull request by ammedmar**
Mostly minor improvements. Just getting it in shape to be presentable.

### CODE REVIEW

**Comment by gf2078** [comment]
I'd still like to cite that work of Thom if that line is still in the current version of the Intro.

**Comment by gf2078** [comment]
Since you're like 4 pull requests ahead of me, I won't try to do my own edits and add them but instead I'll put some suggestions here. You (Anibal) flagged "Several of the major theorems are unproven or have arguments just hinted at." as sound weird. How about "Proofs of several majors theorems are omitted or only hinted at."?

**Comment by gf2078** [comment]
In the line about other examples of geometric cohomology, we should mention Goresky's work on geometric homology and cohomology of Whitney stratified objects (WHITNEY STRATIFIED CHAINS AND COCHAINS BY R. MARK GORESKY) and the book by Buoncristian, Rourke, and Sanderson.

**Comment by gf2078** [comment]
Okay, except for the suggestions above, I'm good with Pull Request #4.

Question: How do I go back to the comments from a completed pull request after it's resolved and merged? For example, I'm no longer seeing requests 1-3 on my panel.

**Comment by ammedmar** [comment]
> I'd still like to cite that work of Thom if that line is still in the current version of the Intro.

Sure, the current version (s1+dev) reads:

Such representation naively posed is an impossible goal due to the seminal work of Thom on bordism theory,
which showed that not all homology classes can be represented by pushing forward fundamental classes of manifolds.

Would you like me to add a citation to the bordism paper of Thom?

> Since you're like 4 pull requests ahead of me, I won't try to do my own edits and add them but instead I'll put some suggestions here. You (Anibal) flagged "Several of the major theorems are unproven or have arguments just hinted at." as sound weird. How about "Proofs of several majors theorems are omitted or only hinted at."?

After Dev it read:

Lipyanskiy's unpublished manuscript \cite{Lipy14} on which we build gives a fairly thorough account of geometric homology, but a much more lightly sketched account of geometric cohomology, which leaves several major theorems  unproven.

If this is not good maybe we can revisit it when looking at PR #5 ?

> In the line about other examples of geometric cohomology, we should mention Goresky's work on geometric homology and cohomology of Whitney stratified objects (WHITNEY STRATIFIED CHAINS AND COCHAINS BY R. MARK GORESKY) and the book by Buoncristian, Rourke, and Sanderson.

I added the missing bib entries and your text above to the latest version of s1. You will review the outcome in PR #5.

> Okay, except for the suggestions above, I'm good with Pull Request #4.

Happy to hear. I will merge it after you OK it (green check mark).

> Question: How do I go back to the comments from a completed pull request after it's resolved and merged? For example, I'm no longer seeing requests 1-3 on my panel.

All PRs are kept. They can be found in the repo [here](https://github.com/ammedmar/foundations/pulls). You will have to select the option "closed" to see those already merged.

**Review by gf2078 — APPROVED** [review]
See previous comments

**Pull request merged**
